baseURL = "https://shaunnewman.com"
languageCode = "en-us"
title = "Shaun Newman"
theme = "pulp"
enableRobotsTXT = true

[taxonomies]
  series = "series"

[params]
    author = "Shaun Newman"
    avatar = "avatar.jpg"
    favicon = "favicon.ico"
    description = """
        Software Engineer currently writing distributed systems in Go.
        Loves talking about Kubernetes, Docker, and Vim (the superior text editor).
    """
    metaDescription = "Shaun Newman is a software engineer writing distributed systems in Go."
    publicationYear = "2026"

[outputs]
    section = ["JSON", "HTML"]

[[menu.main]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/shaun-newman"
    weight = 10
    [menu.main.params]
        icon = "linkedin"

[[menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/scnewma"
    weight = 30
    [menu.main.params]
        icon = "github"
